### ISSUE TITLE
How do you make a plugin that interprets frontmatter config?

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/docfy#67]
I'm wanting to do something like: 

```md
---
order: 1
title: My Title
forEmployeesOnly: true
# or:
newProperty:
  extraConfig:
    interpret this in a befoerModel hook to guard transitions
---
```

I have a service that I can use to determine the "employees only" stuff, but the goal is to:
 - remove from the sidenav (I can do this with an if condition in the template though, as long as the data is there)
 - prevent visiting that URL via a beforeModel hook check
 
 Does the plugin system allow this?

**Comment by josemarluedke** [comment]
You don't necessarily need a plugin to accomplish this. All the frontmatter is extracted and kept in the runtime data.

Since you are using the Docfy Ember, you can use the docfy service to find the page you are trying to access, look at the front matter, and then prevent it. 
For the sidebar, you also have access to that info, therefore, just an if statement should solve that.

Let's use your example. So, for the sidebar, it might look something like this:

```hbs
// stuff
{{#each child.pages as |page|}}
  {{#unless page.frontmatter.forEmployeesOnly}}
    <li class="truncate">
      <DocfyLink @to={{page.url}}>
        {{page.title}}
      </DocfyLink>
    </li>
  {{/unless}}
{{/each}}
// stuff
```

And here how your route could look like:

```ts
import Route from '@ember/routing/route';
import { DocfyService } from '@docfy/ember';
import { inject as service } from '@ember/service';
import RouterService from '@ember/routing/router-service';
type Transition = ReturnType<RouterService['transitionTo']>;

export default class Docs extends Route {
  @service router!: RouterService;
  @service docfy!: DocfyService;

  beforeModel(transition: Transition): void {
    const url = this.router.urlFor(transition.to.name);
    const page = this.docfy.findByUrl(url);
    console.log(page?.frontmatter.forEmployeesOnly);
  }
}
```

I hope this helps.

**Comment by NullVoxPopuli** [comment]
it does! thanks!

I think because I don't want to make a route file for each generated page, I'll need to set up a `router.on('routeWillChange', this.checkEmployeeStatus)` or something like that.

I'm very excited for this. :D eeee

I'll report back with results

**Comment by josemarluedke** [comment]
Excellent. Let me know how it goes.
